/**
 * AUTO-GENERATED by scripts/gen-i18n-types.mjs from src/lib/i18n/dictionaries/en.json.
 * Do not edit by hand — run `npm run i18n:gen-types` to regenerate.
 */
export interface Dictionary {
  home: {
    title: string;
    description: string;
    bilibiliButton: string;
    douyinButton: string;
  };
  unified: {
    pageTitle: string;
    pageDescription: string;
    placeholder: string;
    newBadge: string;
    exampleLabel: string;
    exampleUrl: string;
  };
  page: {
    feedback: string;
    feedbackLinkText: string;
    openMenuLabel: string;
    switchLanguageLabel: string;
    copyrightVideo: string;
    copyrightStorage: string;
    copyrightYear: string;
    copyrightBilibiliRestriction: string;
  };
  form: {
    pasteButton: string;
    downloadButton: string;
    downloading: string;
  };
  errors: {
    emptyUrl: string;
    downloadError: string;
    downloadFailed: string;
    getVideoInfoFailed: string;
    clipboardFailed: string;
    clipboardPermission: string;
    allImagesLoadFailed: string;
    packageFailed: string;
    confirmPartialDownload: string;
    'continue': string;
    cancel: string;
    fileTooLarge: string;
    videoFileTooLarge: string;
    audioFileTooLarge: string;
    totalSizeTooLarge: string;
    fileEmpty: string;
    fileFormatNotSupported: string;
    audioFormatNotSupported: string;
    fileReadFailed: string;
    noVideoSelected: string;
    noAudioSelected: string;
    api: {
      BAD_REQUEST: string;
      INVALID_JSON: string;
      UNSUPPORTED_PLATFORM: string;
      PLATFORM_MISMATCH: string;
      INVALID_DOWNLOAD_TYPE: string;
      INVALID_QUALITY: string;
      NOT_FOUND: string;
      DOWNLOAD_URL_NOT_FOUND: string;
      RATE_LIMITED: string;
      UPSTREAM_ERROR: string;
      SERVICE_UNAVAILABLE: string;
      INTERNAL_ERROR: string;
      FEEDBACK_SUBMIT_FAILED: string;
      MEDIA_PROCESSOR_INIT_FAILED: string;
      PARSE_FAILED: string;
    };
  };
  history: {
    title: string;
    description: string;
    clear: string;
    cleared: string;
    searchPlaceholder: string;
    noSearchResults: string;
    viewSource: string;
    redownload: string;
    linkFilled: string;
    clickToRedownload: string;
    unknownTitle: string;
    pageTitle: string;
    logsCount: string;
    clearHistory: string;
    noRecordsTitle: string;
    cleanBadge: string;
    noRecordsDesc: string;
    autoPersisted: string;
    instantRedownloads: string;
    completed: string;
    details: string;
    detailsTitle: string;
    redownloadZip: string;
    redownloadSingleImage: string;
    redownloadMp4: string;
    redownloadMp3: string;
    removeFromHistory: string;
    queuedForRedownload: string;
    removedJobRecord: string;
    clearedAllHistory: string;
    platforms: {
      bilibili: string;
      bilibiliTv: string;
      douyin: string;
      kuaishou: string;
      youtube: string;
      telegram: string;
      wechat: string;
      niconico: string;
      xiaohongshu: string;
      tiktok: string;
      generic: string;
      unknown: string;
      instagram: string;
      x: string;
      threads: string;
      weibo: string;
      dailymotion: string;
      newgrounds: string;
      okru: string;
      pinterest: string;
      reddit: string;
      soundcloud: string;
      streamable: string;
      twitch: string;
      tumblr: string;
      vk: string;
      vimeo: string;
    };
  };
  toast: {
    linkFilled: string;
    douyinParseSuccess: string;
    linkFilledForRedownload: string;
    clickToRedownloadDesc: string;
    installTitle: string;
    installDescription: string;
    installAction: string;
  };
  metadata: {
    title: string;
    description: string;
    ogTitle: string;
    ogDescription: string;
    siteName: string;
  };
  common: {
    home: string;
    backToTop: string;
    relatedPages: string;
    privacy: string;
    terms: string;
    contact: string;
    trustAndPolicies: string;
  };
  contactPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    intro: string;
    feedback: string;
    feedbackHint: string;
    github: string;
    githubHint: string;
  };
  aboutPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    subtitle: string;
    productInfo: string;
    productName: string;
    publisher: string;
    appVersion: string;
    targetRuntime: string;
    compilationBuild: string;
    thirdPartyLibraries: string;
    thirdPartyDesc: string;
    copyrightNotice: string;
    copyrightTitle: string;
    copyrightSub: string;
    copyrightDesc: string;
    privacyPolicy: string;
    privacyDesc: string;
    responsibleUse: string;
    responsibleUseDesc: string;
  };
  feedbackPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    privateFeedbackTitle: string;
    privateFeedbackDescription: string;
    emailAction: string;
    emailTemplateBody: string;
  };
  privacyPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    intro: string;
    points: string[];
    updated: string;
  };
  termsPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    intro: string;
    points: string[];
    updated: string;
  };
  languages: {
    zh: string;
    'zh-tw': string;
    en: string;
    ja: string;
    es: string;
    ru: string;
  };
  douyin: {
    apiLimitDownload: string;
  };
  extractAudio: {
    button: string;
    loading: string;
    downloading: string;
    downloadingWithSize: string;
    converting: string;
    completed: string;
    retry: string;
    errorLoad: string;
    errorDownload: string;
    errorConvert: string;
    errorMemory: string;
  };
  audioTool: {
    triggerButton: string;
    title: string;
    description: string;
    extractDescription: string;
    mergeDescription: string;
    placeholder: string;
    strategyHint: string;
    pasteButton: string;
    submitButton: string;
    processingButton: string;
    statusIdle: string;
    statusMergeIdle: string;
    statusParsing: string;
    statusPreparingMerge: string;
    statusDirectDownloading: string;
    statusFallbackExtracting: string;
    statusCompleted: string;
    noAudioSource: string;
    noMergeSource: string;
    urlTab: string;
    fileTab: string;
    mergeTab: string;
    videoFile: string;
    audioFile: string;
    dropHint: string;
    fileSizeLimit: string;
    fileSelected: string;
    selectFileButton: string;
    changeFileButton: string;
    selectVideoButton: string;
    selectAudioButton: string;
    videoSizeLimit: string;
    audioSizeLimit: string;
    videoSelected: string;
    audioSelected: string;
    mergeButton: string;
    changeVideoButton: string;
    changeAudioButton: string;
    closeButton: string;
    statusReadingFile: string;
    statusFileReady: string;
    statusReadingVideo: string;
    statusReadingAudio: string;
    statusMerging: string;
  };
  hlsDownload: {
    description: string;
    outputTitle: string;
    outputPlaceholder: string;
    sourceUrl: string;
    sourcePlaceholder: string;
    refererUrl: string;
    refererPlaceholder: string;
    segmentCount: string;
    segmentCountPlaceholder: string;
    resolveButton: string;
    resolvingButton: string;
    downloadButton: string;
    downloadingButton: string;
    statusLabel: string;
    idleStatus: string;
    resolvingStatus: string;
    resolvedStatus: string;
    resolveFailedStatus: string;
    downloadingStatus: string;
    downloadCompletedStatus: string;
    downloadFailedStatus: string;
    largeVideoBrowserLimitedStatus: string;
    progressLabel: string;
    speedLabel: string;
    etaLabel: string;
    calculatingLabel: string;
    confirmCloseTitle: string;
    confirmCloseDescription: string;
    confirmCloseAction: string;
    resolvedPlaylist: string;
    totalSegments: string;
    selectedSegments: string;
    encryptedLabel: string;
    encryptedYes: string;
    encryptedNo: string;
    encryptedHint: string;
    previewSegmentUrls: string;
  };
  guide: {
    quickStart: {
      title: string;
      steps: Array<{
          title: string;
          description: string;
        }>;
    };
    platformSupport: {
      title: string;
      bilibili: {
        name: string;
        summary: string;
        features: string[];
      };
      bilibiliTv: {
        name: string;
        summary: string;
        features: string[];
      };
      douyin: {
        name: string;
        summary: string;
        features: string[];
      };
      hls: {
        name: string;
        summary: string;
        features: string[];
      };
      youtube: {
        name: string;
        summary: string;
        features: string[];
      };
      telegram: {
        name: string;
        summary: string;
        features: string[];
      };
      wechat: {
        name: string;
        summary: string;
        features: string[];
      };
      niconico: {
        name: string;
        summary: string;
        features: string[];
      };
      xiaohongshu: {
        name: string;
        summary: string;
        features: string[];
      };
      tiktok: {
        name: string;
        summary: string;
        features: string[];
      };
      comingSoon: string;
      instagram: {
        name: string;
        summary: string;
        features: string[];
      };
      x: {
        name: string;
        summary: string;
        features: string[];
      };
      threads: {
        name: string;
        summary: string;
        features: string[];
      };
      weibo: {
        name: string;
        summary: string;
        features: string[];
      };
      vimeo: {
        name: string;
        summary: string;
        features: string[];
      };
      dailymotion: {
        name: string;
        summary: string;
        features: string[];
      };
      streamable: {
        name: string;
        summary: string;
        features: string[];
      };
      reddit: {
        name: string;
        summary: string;
        features: string[];
      };
      newgrounds: {
        name: string;
        summary: string;
        features: string[];
      };
      tumblr: {
        name: string;
        summary: string;
        features: string[];
      };
      pinterest: {
        name: string;
        summary: string;
        features: string[];
      };
      vk: {
        name: string;
        summary: string;
        features: string[];
      };
      okru: {
        name: string;
        summary: string;
        features: string[];
      };
      twitch: {
        name: string;
        summary: string;
        features: string[];
      };
      soundcloud: {
        name: string;
        summary: string;
        features: string[];
      };
      applePodcasts: {
        name: string;
        summary: string;
        features: string[];
      };
    };
    linkFormats: {
      title: string;
      bilibili: {
        title: string;
        examples: string[];
      };
      douyin: {
        title: string;
        examples: string[];
      };
      telegram: {
        title: string;
        examples: string[];
      };
      tip: string;
    };
  };
  freeSupport: {
    title: string;
    features: {
      freeToUse: string;
      noRegistration: string;
      unlimitedDownloads: string;
    };
    privacy: {
      title: string;
      noUserRecords: string;
      localStorage: string;
    };
    revenue: {
      adsSupport: string;
      serverCosts: string;
    };
  };
  seo: {
    features: {
      en: string[];
      zh: string[];
      'zh-tw': string[];
      ja: string[];
      es: string[];
      ru: string[];
    };
    howTo: {
      title: {
        en: string;
        zh: string;
        'zh-tw': string;
        ja: string;
        es: string;
        ru: string;
      };
      steps: {
        en: Array<{
            name: string;
            text: string;
          }>;
        zh: Array<{
            name: string;
            text: string;
          }>;
        'zh-tw': Array<{
            name: string;
            text: string;
          }>;
        ja: Array<{
            name: string;
            text: string;
          }>;
        es: Array<{
            name: string;
            text: string;
          }>;
        ru: Array<{
            name: string;
            text: string;
          }>;
      };
    };
  };
  result: {
    title: string;
    downloadVideo: string;
    browserDownloadVideo: string;
    mergeDownloadVideo: string;
    mergeDownloadVideoHint: string;
    downloadAudio: string;
    playVideo: string;
    playAudio: string;
    sharePlayLink: string;
    sharePlayLinkCopied: string;
    previewPlayerTitle: string;
    previewPlayerClose: string;
    sharePlayPlayerTitle: string;
    sharePlayUnavailable: string;
    originDownloadVideo: string;
    originDownloadAudio: string;
    totalParts: string;
    showAllParts: string;
    collapseParts: string;
    loadMoreItems: string;
    shownItems: string;
    collectionSearchPlaceholder: string;
    collectionNoSearchResults: string;
    articleVideoList: string;
    articleVideoCount: string;
    articleVideoUntitled: string;
    downloadImage: string;
    downloadCover: string;
    coverLabel: string;
    imageIndexLabel: string;
    imageAlt: string;
    imageNote: string;
    imageCount: string;
    packaging: string;
    packageDownload: string;
    loading: string;
    loadFailed: string;
    viewLargeImage: string;
    imageLoadingProgress: string;
    imageAutoLoadedTip: string;
    packagingProgress: string;
    videoList: string;
    videoCount: string;
    pureMusicHint: string;
  };
  changelog: {
    title: string;
  };
  feedback: {
    title: string;
    triggerButton: string;
    typeLabel: string;
    typeRequired: string;
    types: {
      bug: string;
      feature: string;
      other: string;
    };
    contentLabel: string;
    contentRequired: string;
    contentTooShort: string;
    contentPlaceholder: {
      bug: string;
      feature: string;
      other: string;
    };
    contentCounter: string;
    emailLabel: string;
    emailPlaceholder: string;
    emailInvalid: string;
    emailRequired: string;
    emailHint: string;
    diagnosticInfoHint: string;
    cancelButton: string;
    submitButton: string;
    submittingButton: string;
    closeButton: string;
    successTitle: string;
    successMessage: string;
    successNote: string;
    errorTitle: string;
    errorMessage: string;
    errorFallback: string;
    retryButton: string;
    toastSuccess: string;
    toastError: string;
  };
  supportedPlatformsModal: {
    title: string;
    badge: string;
    description: string;
    searchPlaceholder: string;
    noSearchResults: string;
    activeStreamer: string;
    active: string;
    fastExtract: string;
    autoDetect: string;
    showingCount: string;
    close: string;
    clickDetails: string;
    clickTitle: string;
    universalSub: string;
  };
  batchWorkspace: {
    title: string;
    subtitle: string;
    queuePreferences: string;
    nav: {
      queueWorkspace: string;
      downloadHistory: string;
      preferences: string;
      aboutVoidFetch: string;
      privacyAndTerms: string;
    };
    composer: {
      title: string;
      subtitlePrefix: string;
      platformsLink: string;
      subtitleSuffix: string;
      pasteClipboard: string;
      importFile: string;
      placeholder: string;
      detectedSingle: string;
      detectedPlural: string;
      dupesCount: string;
      dropFileHint: string;
      copyrightWarning: string;
      feedbackHint: string;
      supportedPlatformsBar: string;
      clear: string;
      addUrls: string;
      addUrlsCount: string;
    };
    toolbar: {
      searchPlaceholder: string;
      allStatus: string;
      allPlatforms: string;
      parseAll: string;
      pauseQueue: string;
      startQueue: string;
      retryFailed: string;
      clearCompleted: string;
      status: {
        all: string;
        draft: string;
        parsing: string;
        ready: string;
        queued: string;
        downloading: string;
        processing: string;
        saving: string;
        paused: string;
        completed: string;
        failed: string;
        cancelled: string;
      };
    };
    queue: {
      emptyTitle: string;
      emptyBadge: string;
      emptyDescription: string;
      multiThreaded: string;
      audioExtraction: string;
      upTo4k: string;
      itemsSelectedSingle: string;
      itemsSelectedPlural: string;
      bulkConfigure: string;
      bulkConfigureCount: string;
      removeSelected: string;
      selectAll: string;
      itemsCount: string;
      noMatchingJobs: string;
    };
    configDrawer: {
      titleSingle: string;
      titleBulk: string;
      subtitle: string;
      outputFormat: string;
      videoQuality: string;
      selectVideoQuality: string;
      qualityNote: string;
      audioQuality: string;
      selectAudioQuality: string;
      filenameTemplate: string;
      outputFilename: string;
      clickTokenHint: string;
      hlsConcurrency: string;
      advancedOptions: string;
      downloadThumbnail: string;
      saveMetadataJson: string;
      forceAudioExtraction: string;
      applyChecked: string;
      applyAll: string;
      saveConfig: string;
    };
    progress: {
      totalItems: string;
      running: string;
      queued: string;
      completed: string;
      failed: string;
      speed: string;
      eta: string;
      queueActive: string;
      queueIdle: string;
    };
    settingsModal: {
      title: string;
      description: string;
      defaultOutputAndQuality: string;
      defaultFormat: string;
      defaultQuality: string;
      downloadDirectoryPath: string;
      browserDefault: string;
      customFolder: string;
      customFolderDesc: string;
      browserDefaultDesc: string;
      resetDefault: string;
      changeFolder: string;
      selectCustomFolder: string;
      directoryTip: string;
      networkConcurrency: string;
      concurrentJobs: string;
      hlsSegmentConcurrency: string;
      savePreferences: string;
    };
  };
  settingsPage: {
    metaTitle: string;
    metaDescription: string;
    title: string;
    subtitle: string;
    resetDefaults: string;
    loading: string;
    downloaderDefaults: string;
    defaultOutputType: string;
    defaultQuality: string;
    selectQuality: string;
    defaultFilenameTemplate: string;
    placeholderTokens: string;
    customDirectoryTitle: string;
    customDirName: string;
    browserDefaultDir: string;
    customDirDesc: string;
    browserDefaultDesc: string;
    resetDefaultDir: string;
    changeFolder: string;
    selectCustomFolder: string;
    concurrencyTitle: string;
    parserConcurrency: string;
    downloadConcurrency: string;
    networkBudget: string;
    networkBudgetDesc: string;
    workflowsTitle: string;
    continueOnError: string;
    continueOnErrorDesc: string;
    autoStartDownloads: string;
    autoStartDownloadsDesc: string;
  };
};
